# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for LiteraryCreation backend (onedir)."""
from PyInstaller.utils.hooks import collect_submodules

hiddenimports = []
hiddenimports += collect_submodules('literarycreation')
hiddenimports += [
    'kuzu',
    'lancedb',
    'jieba',
    'pyarrow',
    'starlette',
    'sse_starlette',
    'anyio',
    'h11',
    'httpcore',
    'fastapi',
    'pydantic',
    'httpx',
    'uvicorn.logging',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.lifespan',
    'uvicorn.lifespan.on',
    'numba',
    'numba.core',
    'numba.core.types',
    'numba.core.typing',
    'numba.targets',
    'llvmlite',
    'llvmlite.binding',
]
hiddenimports += collect_submodules('numba')
hiddenimports += collect_submodules('llvmlite')

a = Analysis(
    ['src/literarycreation/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'pandas',
        'numpy.testing',
        'scipy.optimize',
        'scipy.optimize._highspy',
        'scipy.optimize._shgo_lib',
        'scipy.optimize._lsq',
        'scipy.optimize._trustregion_constr',
        'scipy.optimize._trlib',
        'scipy.sparse',
        'scipy.sparse.linalg',
        'scipy.sparse.csgraph',
        'scipy.linalg',
        'scipy.special',
        'scipy.stats',
        'scipy.stats._rcont',
        'scipy.stats._levy_stable',
        'scipy.ndimage',
        'scipy.interpolate',
        'scipy.fft',
        'scipy.fft._pocketfft',
        'scipy.spatial',
        'scipy.spatial.transform',
        'scipy.constants',
        'scipy._lib.pyprima',
        'scipy._lib.cobyqa',
        'scipy._lib._uarray',
        'scipy._lib.array_api_compat',
        'scipy._lib._array_api',
        'PIL',
        'torch',
        'torchvision',
        'transformers',
        'sklearn',
        'scikit-learn',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='literary-creation-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=['VCRUNTIME140.dll', 'python3.dll', '*.pyd', 'llvmlite*.dll'],
    name='literary-creation-backend',
)
